### ISSUE TITLE
setting @model.elapsed before calling confluent transitions

### ISSUE THREAD

**Issue by LifeIsALesson** [devs-ruby/devs#2]
I get syncing problems at occurrence of confluent transitions. The external transition of my model adds `@elapsed` multiple times if `time == @time_next`. I think the problem is caused by the `remainder` method of the `DEVS::SequentialParallel::SimulatorImpl`. If the `bag` is not empty it gets called without setting `@model.elapsed`, keeping its old value. Since `confluent_transition` itself just calls `external_transition` (by default after calling `internal_transition`) this leads to problems using `@elapsed` at the model, assuming a time period > 0 since last activation.

I just monkey patched the method for my issues (gist: https://gist.github.com/LifeIsALesson/1b0254052eaf2853db5d). 

What do you think?

**Comment by romain1189** [comment]
That's correct, as the default behavior of the confluent transition is to call sequentially the internal and the external transition, the elapsed attribute should be set to 0 since it is intended to be used in the external transition.

Thanks for reporting this bug.
